import { useCallback, useEffect, useState } from "react";
import { ComponentSidebar } from "./ComponentSidebar";
import { ComponentPreview } from "./ComponentPreview";
import type { SelectedElement } from "./ComponentPreview";
import { StylePanel } from "./StylePanel";
import { buildComponentEntries } from "../lib/storyLoader";
import type { ComponentEntry } from "../lib/storyLoader";
import { generateStubs } from "../lib/devApi";
import { isUndoRedoKey, useHistory } from "../lib/useHistory";

/**
 * Stories are discovered via `virtual:dev-workshop/stories`, a virtual module
 * generated by the `devWorkshop()` Vite plugin. The module exports the result
 * of `import.meta.glob(storiesGlob, { eager: true })` resolved in the
 * consumer project's context.
 *
 * TypeScript declaration for this module lives in `virtual.d.ts`.
 */
import storyModules from "virtual:dev-workshop/stories";
import componentModules, { componentsGlob as componentsGlobPattern } from "virtual:dev-workshop/components";

const componentEntries = buildComponentEntries(storyModules as Record<string, unknown>);

type ArgsOverride = Record<string, unknown>;

const LS_SIDEBAR = "devWorkshop.sidebarWidth";
const LS_PANEL = "devWorkshop.panelWidth";
const MIN_SIDEBAR = 180;
const MIN_PANEL = 260;
const MAX_WIDTH = 600;

function readLSNumber(key: string, fallback: number): number {
  if (typeof window === "undefined") return fallback;
  const v = Number(localStorage.getItem(key));
  return Number.isFinite(v) && v > 0 ? v : fallback;
}

const STYLES = `
[data-dev-workshop] {
  --dw-bg: white;
  --dw-bg-soft: #fafafa;
  --dw-bg-input: #f4f4f4;
  --dw-bg-input-hover: #ebebeb;
  --dw-bg-active: #101114;
  --dw-bg-dirty: #fff4f4;
  --dw-bg-canvas: #F4F4F4;
  --dw-text: #101114;
  --dw-text-secondary: #404040;
  --dw-text-muted: #606060;
  --dw-text-subtle: #808080;
  --dw-text-placeholder: #b3b3b3;
  --dw-border: #e5e5e5;
  --dw-border-soft: #f1f1f1;
  --dw-accent: #3b82f6;
  --dw-error: #e6365a;
  --dw-success: #1f9d55;
  --dw-font: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  --dw-font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
/* All chrome styles below are scoped to .dw-* classes only.
   We never cascade into descendants of [data-dev-workshop], because the
   user's components render inside the canvas as descendants too — any
   global rule on button / input / * would leak into them. */
[data-dev-workshop] .dw-mono { font-family: var(--dw-font-mono); }
[data-dev-workshop] .dw-kbd {
  font-family: var(--dw-font-mono);
  background: var(--dw-bg-input);
  padding: 1px 4px;
  border-radius: 3px;
  font-size: 10px;
}

/* Floating card surface: panels sit on the gray workspace with a subtle
   shadow so they read as discrete cards. */
[data-dev-workshop] .dw-card {
  background: var(--dw-bg);
  border-radius: 12px;
  box-shadow: 0 1px 2px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.04);
  overflow: hidden;
}

/* Counter badge (e.g. total components in sidebar header) */
[data-dev-workshop] .dw-badge {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  background: var(--dw-bg-input);
  border-radius: 999px;
  padding: 3px 8px 3px 6px;
  font-family: var(--dw-font-mono);
  font-size: 11px;
  color: var(--dw-text-muted);
  line-height: 1.2;
}
[data-dev-workshop] .dw-badge svg {
  flex-shrink: 0;
  display: block;
}

/* Scroll container with hidden scrollbar (still scrollable). Use on chrome
   panels, never on the canvas — the user's component might rely on visible
   scrollbars. */
[data-dev-workshop] .dw-scroll {
  overflow-y: auto;
  scrollbar-width: none;
}
[data-dev-workshop] .dw-scroll::-webkit-scrollbar {
  width: 0;
  height: 0;
  display: none;
}

/* Native color input wrapper: kill the default browser swatch border that
   shows as an inner rectangle. Apply via class to avoid leaking into the
   consumer's color inputs that render inside the canvas. */
[data-dev-workshop] .dw-color-input {
  appearance: none;
  -webkit-appearance: none;
  border: none;
  padding: 0;
  background: transparent;
  cursor: pointer;
  overflow: hidden;
}
[data-dev-workshop] .dw-color-input::-webkit-color-swatch-wrapper {
  padding: 0;
  border-radius: inherit;
}
[data-dev-workshop] .dw-color-input::-webkit-color-swatch {
  border: none;
  border-radius: inherit;
}
[data-dev-workshop] .dw-color-input::-moz-color-swatch {
  border: none;
  border-radius: inherit;
}

/* Each chrome class is self-contained: includes its own font-family, border:none,
   background, padding, etc. so we don't rely on global resets that would leak
   into the user's components rendered inside the canvas. */

[data-dev-workshop] .dw-input {
  appearance: none;
  -webkit-appearance: none;
  box-sizing: border-box;
  border: none;
  outline: none;
  margin: 0;
  background: var(--dw-bg-input);
  border-radius: 4px;
  padding: 4px 8px;
  font-family: var(--dw-font-mono);
  font-size: 11px;
  line-height: 1.4;
  color: var(--dw-text);
  width: 100%;
  transition: background 120ms;
}
[data-dev-workshop] .dw-input:focus { background: var(--dw-bg-input-hover); }
[data-dev-workshop] .dw-input::placeholder { color: var(--dw-text-placeholder); }
[data-dev-workshop] .dw-input.dw-input-sm { font-size: 10px; padding: 3px 6px; border-radius: 3px; }

[data-dev-workshop] .dw-search {
  appearance: none;
  -webkit-appearance: none;
  box-sizing: border-box;
  border: none;
  outline: none;
  margin: 0;
  background: var(--dw-bg-input);
  border-radius: 6px;
  padding: 8px 12px;
  font-family: var(--dw-font);
  font-size: 13px;
  line-height: 1.4;
  color: var(--dw-text);
  width: 100%;
  transition: background 120ms;
}
[data-dev-workshop] .dw-search:focus { background: var(--dw-bg-input-hover); }
[data-dev-workshop] .dw-search::placeholder { color: var(--dw-text-placeholder); }

[data-dev-workshop] .dw-btn-primary {
  appearance: none;
  box-sizing: border-box;
  cursor: pointer;
  border: none;
  margin: 0;
  background: var(--dw-bg-active);
  color: white;
  font-family: var(--dw-font);
  font-weight: 600;
  font-size: 12px;
  line-height: 1.2;
  padding: 8px 12px;
  border-radius: 6px;
  width: 100%;
  transition: opacity 120ms;
}
[data-dev-workshop] .dw-btn-primary:disabled { opacity: 0.3; cursor: not-allowed; }

[data-dev-workshop] .dw-btn-secondary {
  appearance: none;
  box-sizing: border-box;
  cursor: pointer;
  margin: 0;
  border: 1px solid var(--dw-border);
  background: var(--dw-bg);
  color: var(--dw-text-muted);
  font-family: var(--dw-font);
  font-size: 12px;
  line-height: 1.2;
  padding: 8px 12px;
  border-radius: 6px;
  width: 100%;
  transition: background 120ms;
}
[data-dev-workshop] .dw-btn-secondary:hover:not(:disabled) { background: var(--dw-bg-soft); }
[data-dev-workshop] .dw-btn-secondary:disabled { opacity: 0.3; cursor: not-allowed; }

[data-dev-workshop] .dw-pill {
  appearance: none;
  box-sizing: border-box;
  cursor: pointer;
  border: none;
  margin: 0;
  background: var(--dw-bg-input);
  color: var(--dw-text-muted);
  border-radius: 4px;
  padding: 4px 8px;
  font-family: var(--dw-font-mono);
  font-size: 10px;
  line-height: 1.2;
  transition: background 120ms, color 120ms;
}
[data-dev-workshop] .dw-pill:hover { background: var(--dw-bg-input-hover); }
[data-dev-workshop] .dw-pill[data-active="true"] {
  background: var(--dw-bg-active);
  color: white;
}

/* Medium pill — 32px tall, 12px mono. Used in element-tab controls
   (text-align, fill/hug/fixed). Same family/size as the slider value
   so the panel reads as one consistent set of controls. */
[data-dev-workshop] .dw-pill-md {
  appearance: none;
  box-sizing: border-box;
  cursor: pointer;
  border: none;
  margin: 0;
  background: var(--dw-bg-input);
  color: var(--dw-text-muted);
  border-radius: 6px;
  padding: 0 10px;
  height: 32px;
  font-family: var(--dw-font-mono);
  font-size: 12px;
  font-weight: 500;
  line-height: 1;
  transition: background 120ms, color 120ms;
}
[data-dev-workshop] .dw-pill-md:hover { background: var(--dw-bg-input-hover); }
[data-dev-workshop] .dw-pill-md[data-active="true"] {
  background: var(--dw-bg-active);
  color: white;
}

/* Medium input — 32px tall, 12px mono. Same height as slider for
   consistent rows in the element tab. */
[data-dev-workshop] .dw-input-md {
  appearance: none;
  -webkit-appearance: none;
  box-sizing: border-box;
  border: none;
  outline: none;
  margin: 0;
  background: var(--dw-bg-input);
  border-radius: 8px;
  padding: 0 12px;
  height: 32px;
  font-family: var(--dw-font-mono);
  font-size: 12px;
  line-height: 1;
  color: var(--dw-text);
  width: 100%;
  transition: background 120ms;
}
[data-dev-workshop] .dw-input-md:focus { background: var(--dw-bg-input-hover); }
[data-dev-workshop] .dw-input-md::placeholder { color: var(--dw-text-placeholder); }

[data-dev-workshop] .dw-tab {
  appearance: none;
  box-sizing: border-box;
  cursor: pointer;
  border: none;
  margin: 0;
  background: transparent;
  flex: 1 1 0;
  padding: 10px 16px;
  font-family: var(--dw-font);
  font-size: 13px;
  font-weight: 500;
  line-height: 1.2;
  color: var(--dw-text-subtle);
  transition: background 120ms, color 120ms;
}
[data-dev-workshop] .dw-tab:hover { background: var(--dw-bg-soft); color: var(--dw-text); }
[data-dev-workshop] .dw-tab[data-active="true"] { background: var(--dw-bg-input); color: var(--dw-text); }

/* Sidebar row: container that holds icon-btn (toggle expand) + name-btn (select) */
[data-dev-workshop] .dw-sidebar-row {
  display: flex;
  align-items: stretch;
  border-radius: 8px;
  transition: background 80ms;
}
[data-dev-workshop] .dw-sidebar-row:hover { background: var(--dw-bg-soft); }
[data-dev-workshop] .dw-sidebar-row[data-active="true"] {
  background: var(--dw-bg-input);
}
[data-dev-workshop] .dw-sidebar-icon-btn {
  appearance: none;
  cursor: pointer;
  border: none;
  margin: 0;
  background: transparent;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  flex-shrink: 0;
  color: var(--dw-text-placeholder);
  border-radius: 8px 0 0 8px;
}
[data-dev-workshop] .dw-sidebar-icon-btn:hover { color: var(--dw-text-muted); }
[data-dev-workshop] .dw-sidebar-icon-spacer {
  display: block;
  width: 24px;
  flex-shrink: 0;
}
[data-dev-workshop] .dw-sidebar-name-btn {
  appearance: none;
  cursor: pointer;
  border: none;
  margin: 0;
  background: transparent;
  display: flex;
  align-items: center;
  gap: 6px;
  flex: 1;
  min-width: 0;
  padding: 7px 10px 7px 4px;
  text-align: left;
  font-family: var(--dw-font);
  font-size: 13px;
  line-height: 1.3;
  color: var(--dw-text-muted);
  border-radius: 0 8px 8px 0;
  transition: color 80ms;
}
[data-dev-workshop] .dw-sidebar-row[data-active="true"] .dw-sidebar-name-btn {
  color: var(--dw-text);
  font-weight: 500;
}
[data-dev-workshop] .dw-sidebar-name {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
[data-dev-workshop] .dw-sidebar-count {
  flex-shrink: 0;
  font-family: var(--dw-font-mono);
  font-size: 10px;
  color: var(--dw-text-placeholder);
}
[data-dev-workshop] .dw-sidebar-row.dw-sidebar-row-variant .dw-sidebar-name-btn {
  font-size: 12px;
  padding-left: 30px;
  color: var(--dw-text-subtle);
  border-radius: 8px;
}
[data-dev-workshop] .dw-sidebar-row.dw-sidebar-row-variant {
  border-radius: 8px;
}

/* Square 28-tall icon button — used for + add / - remove and the per-row
   reset (×). Plain ghost look, subtle hover. */
[data-dev-workshop] .dw-icon-btn,
[data-dev-workshop] .dw-reset-btn {
  appearance: none;
  box-sizing: border-box;
  cursor: pointer;
  border: none;
  margin: 0;
  background: transparent;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 24px;
  height: 24px;
  border-radius: 6px;
  color: var(--dw-text-muted);
  transition: background 120ms, color 120ms;
}
[data-dev-workshop] .dw-icon-btn:hover,
[data-dev-workshop] .dw-reset-btn:hover {
  background: var(--dw-bg-input);
  color: var(--dw-text);
}

/* Segmented control: tab switcher in StylePanel header */
[data-dev-workshop] .dw-segments {
  display: flex;
  background: var(--dw-bg-input);
  border-radius: 8px;
  padding: 3px;
  gap: 2px;
}
[data-dev-workshop] .dw-segment {
  appearance: none;
  cursor: pointer;
  border: none;
  margin: 0;
  flex: 1;
  padding: 6px 8px;
  font-family: var(--dw-font);
  font-size: 12px;
  font-weight: 500;
  line-height: 1.3;
  text-align: center;
  border-radius: 6px;
  background: transparent;
  color: var(--dw-text-muted);
  transition: background 120ms, color 120ms, box-shadow 120ms;
}
[data-dev-workshop] .dw-segment:hover { color: var(--dw-text); }
[data-dev-workshop] .dw-segment[data-active="true"] {
  background: var(--dw-bg);
  color: var(--dw-text);
  box-shadow: 0 1px 2px rgba(0,0,0,0.04), 0 1px 3px rgba(0,0,0,0.06);
}

/* Slider — full-bleed track with inline label/value, hover ticks, decile-snap.
   See Slider.tsx for behavior; styles cover the resting and hover/active
   states. */
[data-dev-workshop] .dw-slider {
  position: relative;
  flex: 1;
  width: 100%;
  height: 32px;
  border-radius: 8px;
  background: #f1f1f1;
  cursor: ew-resize;
  user-select: none;
  overflow: hidden;
  transition: background 120ms;
}
[data-dev-workshop] .dw-slider[data-hover="true"] { background: #ececec; }
[data-dev-workshop] .dw-slider[data-active="true"] { background: #e5e5e5; }

[data-dev-workshop] .dw-slider-fill {
  position: absolute;
  top: 0; bottom: 0; left: 0;
  background: #d4d4d4;
  pointer-events: none;
  transition: background 120ms;
}
[data-dev-workshop] .dw-slider[data-hover="true"] .dw-slider-fill { background: #c4c4c4; }
[data-dev-workshop] .dw-slider[data-active="true"] .dw-slider-fill { background: #b8b8b8; }

[data-dev-workshop] .dw-slider-handle {
  position: absolute;
  top: 6px; bottom: 6px;
  width: 3px;
  margin-left: -1.5px;
  border-radius: 2px;
  background: #ffffff;
  pointer-events: none;
  transform-origin: center;
  transition: transform 180ms cubic-bezier(0.2, 0, 0.15, 1.6), opacity 120ms;
  box-shadow: 0 1px 2px rgba(0,0,0,0.15);
  opacity: 0;
}
[data-dev-workshop] .dw-slider-handle[data-visible="true"] { opacity: 1; }

[data-dev-workshop] .dw-slider-ticks {
  position: absolute;
  inset: 0;
  pointer-events: none;
  opacity: 0;
  transition: opacity 160ms;
}
[data-dev-workshop] .dw-slider-ticks[data-visible="true"] { opacity: 1; }
[data-dev-workshop] .dw-slider-tick {
  position: absolute;
  top: 50%;
  width: 1px;
  height: 6px;
  margin-left: -0.5px;
  background: rgba(0,0,0,0.16);
  transform: translateY(-50%);
}

[data-dev-workshop] .dw-slider-content {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 12px;
  pointer-events: none;
  gap: 8px;
}
[data-dev-workshop] .dw-slider-label {
  font-family: var(--dw-font);
  font-size: 12px;
  font-weight: 500;
  color: var(--dw-text-secondary);
  pointer-events: none;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
[data-dev-workshop] .dw-slider-value {
  font-family: var(--dw-font-mono);
  font-size: 12px;
  font-weight: 500;
  color: var(--dw-text);
  pointer-events: auto;
  cursor: text;
  white-space: nowrap;
}
[data-dev-workshop] .dw-slider-input {
  appearance: none;
  -webkit-appearance: none;
  border: none;
  outline: none;
  background: white;
  border-radius: 4px;
  margin: 0;
  padding: 2px 6px;
  font-family: var(--dw-font-mono);
  font-size: 12px;
  font-weight: 500;
  color: var(--dw-text);
  width: 84px;
  text-align: right;
  pointer-events: auto;
  box-shadow: 0 0 0 1.5px var(--dw-accent);
}

[data-dev-workshop] .dw-section-label {
  font-family: var(--dw-font);
  font-size: 10px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--dw-text-placeholder);
  line-height: 1.2;
}

[data-dev-workshop] .dw-link {
  appearance: none;
  cursor: pointer;
  border: none;
  margin: 0;
  padding: 0;
  background: transparent;
  font-family: var(--dw-font);
  font-size: 10px;
  line-height: 1.2;
  color: var(--dw-text-muted);
  transition: color 120ms;
}
[data-dev-workshop] .dw-link:hover { color: var(--dw-text); }

[data-dev-workshop] .dw-ghost {
  appearance: none;
  box-sizing: border-box;
  cursor: pointer;
  border: none;
  margin: 0;
  background: var(--dw-bg-input);
  color: var(--dw-text-muted);
  font-family: var(--dw-font);
  font-size: 9px;
  line-height: 1.2;
  padding: 2px 8px;
  border-radius: 3px;
  transition: background 120ms, color 120ms;
}
[data-dev-workshop] .dw-ghost:hover { background: var(--dw-bg-input-hover); color: var(--dw-text); }

/* Resize handle: invisible drag area between floating panels.
   A subtle accent line shows on hover so the user discovers it. */
[data-dev-workshop] .dw-resize {
  appearance: none;
  box-sizing: border-box;
  border: none;
  margin: 0;
  padding: 0;
  width: 12px;
  flex-shrink: 0;
  cursor: ew-resize;
  background: transparent;
  align-self: stretch;
  position: relative;
}
[data-dev-workshop] .dw-resize::after {
  content: "";
  position: absolute;
  top: 50%;
  left: 50%;
  width: 2px;
  height: 28px;
  border-radius: 1px;
  background: var(--dw-border);
  transform: translate(-50%, -50%);
  opacity: 0;
  transition: opacity 120ms, background 120ms;
}
[data-dev-workshop] .dw-resize:hover::after {
  opacity: 1;
  background: var(--dw-accent);
}
`;

export interface DevWorkshopPageProps {
  /** Path to the project's main CSS file (Tokens tab "Save" button).
   *  Defaults to `"src/index.css"`. */
  tokensCssFile?: string;
}

export type Tab = "props" | "tokens" | "code" | "element";

export default function DevWorkshopPage({ tokensCssFile = "src/index.css" }: DevWorkshopPageProps) {
  const [selected, setSelected] = useState<ComponentEntry | null>(componentEntries[0] ?? null);
  const [variantIndex, setVariantIndex] = useState(0);
  const [variantExplicit, setVariantExplicit] = useState(false);
  const argsOverrideH = useHistory<ArgsOverride>({});
  const argsOverride = argsOverrideH.value;
  const setArgsOverride = argsOverrideH.set;
  const [selectedEl, setSelectedEl] = useState<SelectedElement | null>(null);
  const [outlineHidden, setOutlineHidden] = useState(false);
  const [tab, setTab] = useState<Tab>("props");

  // Cmd+Z / Cmd+Shift+Z while Props tab is active → undo/redo args overrides.
  useEffect(() => {
    if (tab !== "props") return;
    const onKey = (e: KeyboardEvent) => {
      const action = isUndoRedoKey(e);
      if (!action) return;
      e.preventDefault();
      if (action === "undo") argsOverrideH.undo();
      else argsOverrideH.redo();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [tab, argsOverrideH]);

  const [sidebarWidth, setSidebarWidth] = useState(() => readLSNumber(LS_SIDEBAR, 240));
  const [panelWidth, setPanelWidth] = useState(() => readLSNumber(LS_PANEL, 360));

  useEffect(() => localStorage.setItem(LS_SIDEBAR, String(sidebarWidth)), [sidebarWidth]);
  useEffect(() => localStorage.setItem(LS_PANEL, String(panelWidth)), [panelWidth]);

  const handleSelect = useCallback((entry: ComponentEntry, variantIdx: number | null = null) => {
    setSelected(entry);
    setVariantIndex(variantIdx ?? 0);
    setVariantExplicit(variantIdx !== null);
    argsOverrideH.reset({});
    setSelectedEl(null);
    setOutlineHidden(false);
  }, [argsOverrideH]);

  const handleVariantChange = useCallback((i: number) => {
    setVariantIndex(i);
    setVariantExplicit(true);
    argsOverrideH.reset({});
    setSelectedEl(null);
    setOutlineHidden(false);
  }, [argsOverrideH]);

  // Auto-switch to Element tab when something is selected via canvas click
  useEffect(() => {
    if (selectedEl) setTab("element");
  }, [selectedEl]);

  const inspectMode = tab === "element";

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== "Escape") return;
      // On Element tab, Esc exits inspect mode and goes back to Props.
      if (tab === "element") {
        setTab("props");
        setSelectedEl(null);
        return;
      }
      if (selectedEl && !outlineHidden) setOutlineHidden(true);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [selectedEl, outlineHidden, tab]);

  useEffect(() => { if (selectedEl) setOutlineHidden(false); }, [selectedEl?.element]);

  // Keep selectedEl.element in sync with live DOM after HMR-driven remounts.
  useEffect(() => {
    const src = selectedEl?.source;
    if (!src) return;
    const selector = `[data-devsource="${src.file}:${src.line}:${src.column}"]`;
    const resolve = () => {
      const fresh = document.querySelector(selector);
      if (!fresh || fresh === selectedEl?.element) return;
      setSelectedEl({ element: fresh, source: src });
    };
    const root = document.querySelector("[data-dev-workshop]") ?? document.body;
    const mo = new MutationObserver(resolve);
    mo.observe(root, { childList: true, subtree: true, attributes: true });
    resolve();
    return () => mo.disconnect();
  }, [selectedEl?.source, selectedEl?.element]);

  const startResize = (which: "sidebar" | "panel") => (e: React.MouseEvent) => {
    e.preventDefault();
    const startX = e.clientX;
    const startW = which === "sidebar" ? sidebarWidth : panelWidth;
    const sign = which === "sidebar" ? 1 : -1;
    const onMove = (ev: MouseEvent) => {
      const next = Math.max(which === "sidebar" ? MIN_SIDEBAR : MIN_PANEL, Math.min(MAX_WIDTH, startW + (ev.clientX - startX) * sign));
      if (which === "sidebar") setSidebarWidth(Math.round(next));
      else setPanelWidth(Math.round(next));
    };
    const onUp = () => { window.removeEventListener("mousemove", onMove); window.removeEventListener("mouseup", onUp); document.body.style.cursor = ""; };
    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onUp);
    document.body.style.cursor = "ew-resize";
  };

  if (!selected) {
    return (
      <>
        <style>{STYLES}</style>
        <NoStoriesState />
      </>
    );
  }

  return (
    <>
      <style>{STYLES}</style>
      <div data-dev-workshop style={{ position: "fixed", inset: 0, zIndex: 0, display: "flex", background: "#F4F4F4", color: "#101114", padding: 12, gap: 0 }}>
        <ComponentSidebar
          entries={componentEntries}
          selectedId={selected.id}
          variantIndex={variantIndex}
          variantExplicit={variantExplicit}
          width={sidebarWidth}
          onSelect={handleSelect}
        />
        <button className="dw-resize" onMouseDown={startResize("sidebar")} title="Drag to resize" aria-label="resize sidebar" />
        <ComponentPreview
          key={selected.id}
          entry={selected}
          variantIndex={variantIndex}
          onVariantChange={handleVariantChange}
          argsOverride={argsOverride}
          selected={selectedEl}
          onSelectElement={setSelectedEl}
          hideSelectionOutline={outlineHidden}
          inspectMode={inspectMode}
        />
        <button className="dw-resize" onMouseDown={startResize("panel")} title="Drag to resize" aria-label="resize panel" />
        <div style={{ width: panelWidth, display: "flex", height: "100%", flexShrink: 0 }}>
          <StylePanel
            entry={selected}
            variantIndex={variantIndex}
            argsOverride={argsOverride}
            onArgsOverrideChange={setArgsOverride}
            selectedElement={selectedEl}
            onDeselectElement={() => setSelectedEl(null)}
            tokensCssFile={tokensCssFile}
            tab={tab}
            onTabChange={setTab}
          />
        </div>
      </div>
    </>
  );
}

/**
 * Empty state shown when no `*.stories.tsx` files were found by the
 * `storiesGlob`. Offers a one-click "Generate stubs" action that walks
 * the consumer's `componentsGlob` and writes stub stories next to each
 * default-exported component. After a successful run we reload — Vite
 * picks up the new files and the workshop fills with components.
 */
function NoStoriesState() {
  type Status = "idle" | "running" | "done" | "error";
  const [status, setStatus] = useState<Status>("idle");
  const [message, setMessage] = useState<string>("");

  const componentFiles = Object.keys(componentModules);
  const hasComponents = componentFiles.length > 0;

  const onGenerate = useCallback(async () => {
    setStatus("running");
    setMessage(`Scanning ${componentFiles.length} files…`);
    try {
      const result = await generateStubs(componentFiles);
      const skippedExisting = result.skipped.filter((s) => s.reason === "stories file already exists").length;
      const skippedOther = result.skipped.length - skippedExisting;
      const parts = [
        `Created ${result.created.length} stub${result.created.length === 1 ? "" : "s"}.`,
        skippedExisting ? `${skippedExisting} already had stories.` : null,
        skippedOther ? `${skippedOther} skipped (no default-exported component).` : null,
      ].filter(Boolean);
      setStatus("done");
      setMessage(parts.join(" "));
      if (result.created.length > 0) {
        setTimeout(() => window.location.reload(), 800);
      }
    } catch (err) {
      setStatus("error");
      setMessage(err instanceof Error ? err.message : String(err));
    }
  }, [componentFiles]);

  return (
    <>
      <div data-dev-workshop style={{ position: "fixed", inset: 0, zIndex: 0, display: "flex", alignItems: "center", justifyContent: "center", background: "#F4F4F4", color: "#101114" }}>
        <div style={{ textAlign: "center", maxWidth: 460, padding: 24 }}>
          <div style={{ fontSize: 22, fontWeight: 600 }}>No stories found yet</div>
          <div style={{ marginTop: 8, fontSize: 14, color: "#606060", lineHeight: 1.5 }}>
            Stories are <code className="dw-mono">*.stories.tsx</code> files placed next to your components.
            {hasComponents
              ? <> We found <strong>{componentFiles.length}</strong> component file{componentFiles.length === 1 ? "" : "s"} matching <code className="dw-mono">{componentsGlobPattern}</code>. Generate stub stories for them and you'll be up and running in a second.</>
              : <> No component files match <code className="dw-mono">{componentsGlobPattern}</code> — adjust the <code className="dw-mono">componentsGlob</code> plugin option, or write a stories file by hand. See the README for the format.</>
            }
          </div>

          {hasComponents && (
            <button
              onClick={onGenerate}
              disabled={status === "running" || status === "done"}
              className="dw-btn-primary"
              style={{ marginTop: 20, width: "auto", padding: "10px 18px", fontSize: 13 }}
            >
              {status === "running" ? "Generating…" : status === "done" ? "Reloading…" : "Generate stubs from " + componentsGlobPattern}
            </button>
          )}

          {message && (
            <div style={{ marginTop: 14, fontSize: 12, color: status === "error" ? "#e6365a" : "#1f9d55", lineHeight: 1.5 }}>
              {message}
            </div>
          )}
        </div>
      </div>
    </>
  );
}
