import { useCallback, useEffect, useState } from "react";
import { ComponentSidebar } from "./ComponentSidebar";
import { ComponentPreview } from "./ComponentPreview";
import type { SelectedElement } from "./ComponentPreview";
import { StylePanel } from "./StylePanel";
import { buildComponentEntries } from "../lib/storyLoader";
import type { ComponentEntry } from "../lib/storyLoader";

/**
 * Stories are discovered via `virtual:dev-workshop/stories`, a virtual module
 * generated by the `devWorkshop()` Vite plugin. The module exports the result
 * of `import.meta.glob(storiesGlob, { eager: true })` resolved in the
 * consumer project's context.
 *
 * TypeScript declaration for this module lives in `virtual.d.ts`.
 */
import storyModules from "virtual:dev-workshop/stories";

const componentEntries = buildComponentEntries(storyModules as Record<string, unknown>);

type ArgsOverride = Record<string, unknown>;

const LS_SIDEBAR = "devWorkshop.sidebarWidth";
const LS_PANEL = "devWorkshop.panelWidth";
const MIN_SIDEBAR = 180;
const MIN_PANEL = 260;
const MAX_WIDTH = 600;

function readLSNumber(key: string, fallback: number): number {
  if (typeof window === "undefined") return fallback;
  const v = Number(localStorage.getItem(key));
  return Number.isFinite(v) && v > 0 ? v : fallback;
}

export interface DevWorkshopPageProps {
  /** Path to the project's main CSS file (Tokens tab "Save" button).
   *  Defaults to `"src/index.css"`. */
  tokensCssFile?: string;
}

export default function DevWorkshopPage({ tokensCssFile = "src/index.css" }: DevWorkshopPageProps) {
  const [selected, setSelected] = useState<ComponentEntry | null>(componentEntries[0] ?? null);
  const [variantIndex, setVariantIndex] = useState(0);
  const [argsOverride, setArgsOverride] = useState<ArgsOverride>({});
  const [selectedEl, setSelectedEl] = useState<SelectedElement | null>(null);
  const [outlineHidden, setOutlineHidden] = useState(false);

  const [sidebarWidth, setSidebarWidth] = useState(() => readLSNumber(LS_SIDEBAR, 240));
  const [panelWidth, setPanelWidth] = useState(() => readLSNumber(LS_PANEL, 360));

  useEffect(() => localStorage.setItem(LS_SIDEBAR, String(sidebarWidth)), [sidebarWidth]);
  useEffect(() => localStorage.setItem(LS_PANEL, String(panelWidth)), [panelWidth]);

  const handleSelect = useCallback((entry: ComponentEntry, variantIdx = 0) => {
    setSelected(entry);
    setVariantIndex(variantIdx);
    setArgsOverride({});
    setSelectedEl(null);
    setOutlineHidden(false);
  }, []);

  const handleVariantChange = useCallback((i: number) => {
    setVariantIndex(i);
    setArgsOverride({});
    setSelectedEl(null);
    setOutlineHidden(false);
  }, []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== "Escape") return;
      if (selectedEl && !outlineHidden) setOutlineHidden(true);
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [selectedEl, outlineHidden]);

  useEffect(() => { if (selectedEl) setOutlineHidden(false); }, [selectedEl?.element]);

  // Keep selectedEl.element in sync with live DOM after HMR-driven remounts.
  useEffect(() => {
    const src = selectedEl?.source;
    if (!src) return;
    const selector = `[data-devsource="${src.file}:${src.line}:${src.column}"]`;
    const resolve = () => {
      const fresh = document.querySelector(selector);
      if (!fresh || fresh === selectedEl?.element) return;
      setSelectedEl({ element: fresh, source: src });
    };
    const root = document.querySelector("[data-dev-workshop]") ?? document.body;
    const mo = new MutationObserver(resolve);
    mo.observe(root, { childList: true, subtree: true, attributes: true });
    resolve();
    return () => mo.disconnect();
  }, [selectedEl?.source, selectedEl?.element]);

  const startResize = (which: "sidebar" | "panel") => (e: React.MouseEvent) => {
    e.preventDefault();
    const startX = e.clientX;
    const startW = which === "sidebar" ? sidebarWidth : panelWidth;
    const sign = which === "sidebar" ? 1 : -1;
    const onMove = (ev: MouseEvent) => {
      const next = Math.max(which === "sidebar" ? MIN_SIDEBAR : MIN_PANEL, Math.min(MAX_WIDTH, startW + (ev.clientX - startX) * sign));
      if (which === "sidebar") setSidebarWidth(Math.round(next));
      else setPanelWidth(Math.round(next));
    };
    const onUp = () => { window.removeEventListener("mousemove", onMove); window.removeEventListener("mouseup", onUp); document.body.style.cursor = ""; };
    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onUp);
    document.body.style.cursor = "ew-resize";
  };

  if (!selected) {
    return (
      <div className="fixed inset-0 z-0 flex items-center justify-center bg-white text-[#101114]">
        <div className="text-center">
          <div className="text-lg font-semibold">No stories found</div>
          <div className="mt-2 text-sm text-[#808080]">
            Create a <code className="font-mono">*.stories.tsx</code> file under <code className="font-mono">src/components/</code>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 z-0 flex bg-white text-[#101114]" data-dev-workshop>
      <ComponentSidebar
        entries={componentEntries}
        selectedId={selected.id}
        variantIndex={variantIndex}
        width={sidebarWidth}
        onSelect={handleSelect}
      />
      <ResizeHandle onMouseDown={startResize("sidebar")} />
      <ComponentPreview
        key={selected.id}
        entry={selected}
        variantIndex={variantIndex}
        onVariantChange={handleVariantChange}
        argsOverride={argsOverride}
        selected={selectedEl}
        onSelectElement={setSelectedEl}
        hideSelectionOutline={outlineHidden}
      />
      <ResizeHandle onMouseDown={startResize("panel")} />
      <div style={{ width: panelWidth }} className="flex h-full shrink-0">
        <StylePanel
          entry={selected}
          variantIndex={variantIndex}
          argsOverride={argsOverride}
          onArgsOverrideChange={setArgsOverride}
          selectedElement={selectedEl}
          onDeselectElement={() => setSelectedEl(null)}
          tokensCssFile={tokensCssFile}
        />
      </div>
    </div>
  );
}

function ResizeHandle({ onMouseDown }: { onMouseDown: (e: React.MouseEvent) => void }) {
  return <div onMouseDown={onMouseDown} title="Drag to resize" className="group flex w-1 shrink-0 cursor-ew-resize items-stretch bg-[#e5e5e5] hover:bg-[#3b82f6]" />;
}
